version: "3.8"

networks:
  workspaces:

services:
  react-app-a:
    build:
      context: .
      dockerfile: ./react-app-a/dockerfile
    image: react-app-a:latest
    container_name: react-app-a
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - workspaces
    volumes: 
      - ./react-app-a:/app/react-app-a
      - ./common:/app/common