FROM node:16.17.0

WORKDIR /app

COPY ./react-app-a/package.json ./react-app-a/package.json
COPY ./@csl/components/package.json ./@csl/components/package.json
COPY ./@csl/interfaces/package.json ./@csl/interfaces/package.json
COPY ./@csl/functions/package.json ./@csl/functions/package.json
COPY ./package.json ./

RUN npm install

COPY ./react-app-a/src ./react-app-a/src
COPY ./@csl ./@csl


CMD ["npm", "run", "app", "react-app-a"]