FROM node:16.17.0

WORKDIR /app

COPY ./express-api-a/package.json ./express-api-a/package.json
COPY ./@csl/interfaces/package.json ./@csl/interfaces/package.json
COPY ./@csl/functions/package.json ./@csl/functions/package.json
COPY ./package.json ./

RUN npm install

COPY ./express-api-a/src/ ./express-api-a/src/
COPY ./@csl ./@csl

CMD ["npm", "run", "app", "express-api-a"]